input.onButtonPressed(Button.A, function () {
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(349, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(494, music.beat(BeatFraction.Whole))
    basic.pause(200)
    music.playTone(440, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(392, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(330, music.beat(BeatFraction.Whole))
    basic.pause(100)
    music.playTone(262, music.beat(BeatFraction.Whole))
    basic.pause(500)
})
